alias: Notify daily of Chickamauga Lake Level
description: ""
triggers:
  - trigger: time
    at: "08:00:00"
    weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
conditions:
  - condition: numeric_state
    entity_id: sensor.chickamauga_level_difference
    below: -0.5
    above: -4
  - condition: template
    value_template: "{{ now().month in [4,5,6] }}"
actions:
  - action: notify.notify
    metadata: {}
    data:
      message: >-
        Chickamauga Lake is at {{states.sensor.chickamauga_lake_level.state}}ft,
        which is {{states.sensor.chickamauga_level_difference.state}}ft below
        full pool.
mode: single
